#' Summarise all n-grams in response text by frequency
#'
#' @param data data frame containing response text for all questions.
#' @param clean_text_fn function used to clean question text.
#' @param glossary_words character vector of multi-word terms to be replaced
#'   with single word equivalents (set to NULL to ignore).
#' @param stop_words character vector of common words to be removed from
#'   un-nested values (set to NULL to ignore).
#' @param n named list where names are the n-gram types and values are the
#'   the number of terms (default is `list("bi-gram" = 2, "tri-gram" = 3)`).
#'
#' @return named list of lists where names are n-gram types and
#'   values are named lists where names are questions and values n-gram counts.
#' @export
#'
summarise_ngrams <- function(
    data,
    clean_text_fn,
    glossary_words,
    stop_words,
    n = list("bi-gram" = 2, "tri-gram" = 3)) {
  assert_data_frame(data)
  assert_function(clean_text_fn)
  assert_character(glossary_words, null.ok = TRUE)
  assert_character(stop_words, null.ok = TRUE)
  assert_list(n, types = c("integerish"), names = "named")

  cols_free_text <- names(data)

  fn_n <- function(df, col, ngram_type) {
    unnest_ngrams(
      df,
      col,
      n[[ngram_type]],
      clean_text_fn,
      glossary_words = glossary_words,
      stop_words = stop_words,
      col_word = ngram_type,
      n_min = 2
    )
  }

  ngram_list <- names(n)

  list_out <- ngram_list |>
    rlang::set_names(ngram_list) |>
    purrr::map(
      \(x) get_token_counts(data, cols_free_text, \(d, c) fn_n(d, c, x))
    )

  return(list_out)
}


#' Helper function to view n-gram summary
#'
#' @param ngram_list named list of lists where names are n-gram types and
#'   values are named lists where names are questions and values n-gram counts
#'   (generated by [summarise_ngrams()]).
#'
#' @return passed `ngram_list`
#' @export
#'
view_ngram_summary <- function(ngram_list) {
  assert_list(ngram_list, types = c("list"), names = "named")

  for (token_type in names(ngram_list)) {
    view_token_counts(ngram_list[[token_type]], token_type)
  }
  return(invisible(ngram_list))
}


#' Helper function to plot frequency graphs of n-gram summary
#'
#' @param ngram_list named list of lists where names are n-gram types and
#'   values are named lists where names are questions and values n-gram counts
#'   (generated by [summarise_ngrams()]).
#' @param plot_rows integer number of terms to display on plots.
#'
#' @return passed `ngram_list`
#' @export
#'
plot_ngram_summary <- function(ngram_list, plot_rows = 30) {
  assert_list(ngram_list, types = c("list"), names = "named")
  assert_integerish(plot_rows, max.len = 1)

  for (token_type in names(ngram_list)) {
    plot_token_counts(ngram_list[[token_type]], plot_rows)
  }
  return(invisible(ngram_list))
}


#' Helper function to save n-gram summary output to folder
#'
#' @param ngram_list named list of lists where names are n-gram types and
#'   values are named lists where names are questions and values n-gram counts
#'   (generated by [summarise_ngrams()]).
#' @param folder path to the folder in which to save (will create if not
#'   present).
#' @param plot_rows integer number of terms to display on plots.
#' @param prefix  prefix to use when naming files (defaults to
#'   `basename(folder)`).
#'
#' @return passed `ngram_list`
#' @export
#'
write_ngram_summary <- function(
    ngram_list,
    folder,
    plot_rows = 30,
    prefix = basename(folder)) {
  assert_list(ngram_list, types = c("list"), names = "named")
  assert_string(folder)
  assert_integerish(plot_rows, max.len = 1)
  assert_string(prefix)

  for (token_type in names(ngram_list)) {
    write_token_counts(
      ngram_list[[token_type]], folder, token_type, plot_rows, prefix
    )
  }
  return(invisible(ngram_list))
}
