#' Summarise all raw words in response text by frequency
#'
#' @param data data frame containing response text for all questions.
#' @param glossary_words character vector of multi-word terms to be replaced
#'   with single word equivalents (set to NULL to ignore).
#'
#' @return named list of data frame where names are questions and values are
#'   raw word counts
#' @export
#'
summarise_raw_words <- function(
    data,
    glossary_words) {
  assert_data_frame(data)
  assert_character(glossary_words, null.ok = TRUE)

  text_cleaner <- \(x) stringr::str_replace_all(x, "[^0-9a-zA-Z'\\s]", "")

  stop_words <- c(
    tidytext::stop_words$word,
    stringr::str_to_title(tidytext::stop_words$word)
  )

  cols_free_text <- names(data)

  fn <- function(df, col) {
    unnest_words(
      df,
      col,
      text_cleaner,
      glossary_words = glossary_words,
      stop_words = stop_words,
      stem_word_exceptions = NULL,
      col_word = "word",
      min_char = 1
    )
  }

  df_out <- get_token_counts(data, cols_free_text, fn)

  return(df_out)
}


#' Helper function to view raw word summary
#'
#' @param count_list named list of data frame where names are questions and
#'   values are word counts (generated by [summarise_raw_words()]).
#'
#' @return passed `count_list`
#' @export
#'
view_raw_word_summary <- function(count_list) {
  assert_list(count_list, names = "named")

  view_token_counts(count_list, "word")
  return(invisible(count_list))
}


#' Helper function to plot frequency graphs of raw word summary
#'
#' @param count_list named list of data frame where names are questions and
#'   values are word counts (generated by [summarise_raw_words()]).
#' @param plot_rows integer number of terms to display on plots.
#'
#' @return passed `count_list`
#' @export
#'
plot_raw_word_summary <- function(count_list, plot_rows = 30) {
  assert_list(count_list, names = "named")
  assert_integerish(plot_rows, max.len = 1)

  plot_token_counts(count_list, plot_rows)
  return(invisible(count_list))
}


#' Helper function to save raw word summary output to folder
#'
#' @param count_list named list of data frame where names are questions and
#'   values are word counts (generated by [summarise_raw_words()]).
#' @param folder path to the folder in which to save (will create if not
#'   present).
#' @param plot_rows integer number of terms to display on plots.
#' @param prefix  prefix to use when naming files (defaults to
#'   `basename(folder)`).
#'
#' @return passed `count_list`
#' @export
#'
write_raw_word_summary <- function(
    count_list,
    folder,
    plot_rows = 30,
    prefix = basename(folder)) {
  assert_list(count_list, names = "named")
  assert_string(folder)
  assert_integerish(plot_rows, max.len = 1)
  assert_string(prefix)

  write_token_counts(count_list, folder, "word", plot_rows, prefix)

  return(invisible(count_list))
}
