#' Summarise all words in response text by frequency
#'
#' @param data data frame containing response text for all questions.
#' @param clean_text_fn function used to clean question text.
#' @param stop_words character vector of common words to be removed from
#'   un-nested values (set to NULL to ignore).
#' @param glossary_words character vector of multi-word terms to be replaced
#'   with single word equivalents (set to NULL to ignore).
#' @param min_char minimum number of characters needed to be included in
#'   analysis (default = 2).
#'
#' @return named list of data frame where names are questions and values are
#'   word counts
#' @export
#'
summarise_words <- function(
    data,
    clean_text_fn,
    glossary_words,
    stop_words,
    min_char = 2) {
  assert_data_frame(data)
  assert_function(clean_text_fn)
  assert_character(glossary_words, null.ok = TRUE)
  assert_character(stop_words, null.ok = TRUE)
  assert_integerish(min_char, lower = 1, max.len = 1)

  cols_free_text <- names(data)

  fn <- function(df, col) {
    unnest_words(
      df,
      col,
      clean_text_fn,
      glossary_words = glossary_words,
      stop_words = stop_words,
      stem_word_exceptions = NULL,
      col_word = "word",
      min_char = min_char
    )
  }

  df_out <- get_token_counts(data, cols_free_text, fn)

  return(df_out)
}


#' Helper function to view word summary
#'
#' @param count_list named list of data frame where names are questions and
#'   values are word counts (generated by [summarise_words()]).
#'
#' @return passed `count_list`
#' @export
#'
view_word_summary <- function(count_list) {
  assert_list(count_list, names = "named")

  view_token_counts(count_list, "word")
  return(invisible(count_list))
}


#' Helper function to plot frequency graphs of word summary
#'
#' @param count_list named list of data frame where names are questions and
#'   values are word counts (generated by [summarise_words()]).
#' @param plot_rows integer number of terms to display on plots.
#'
#' @return passed `count_list`
#' @export
#'
plot_word_summary <- function(count_list, plot_rows = 30) {
  assert_list(count_list, names = "named")
  assert_integerish(plot_rows, max.len = 1)

  plot_token_counts(count_list, plot_rows)
  return(invisible(count_list))
}


#' Helper function to save word summary output to folder
#'
#' @param count_list named list of data frame where names are questions and
#'   values are word counts (generated by [summarise_words()]).
#' @param folder path to the folder in which to save (will create if not
#'   present).
#' @param plot_rows integer number of terms to display on plots.
#' @param prefix  prefix to use when naming files (defaults to
#'   `basename(folder)`).
#'
#' @return passed `count_list`
#' @export
#'
write_word_summary <- function(
    count_list,
    folder,
    plot_rows = 30,
    prefix = basename(folder)) {
  assert_list(count_list, names = "named")
  assert_string(folder)
  assert_integerish(plot_rows, max.len = 1)
  assert_string(prefix)

  write_token_counts(count_list, folder, "word", plot_rows, prefix)

  return(invisible(count_list))
}
